name: tests run prototype

on:
  workflow_dispatch:
  push:
    paths:
    - 'requirements/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # checkout changes
      - uses: actions/checkout@v2

      # check that conforms to V-238204
#       - name: "V-238204"
#         run: cat /etc/pam.d/login && grep pam_lastlog /etc/pam.d/login
          
      - name: Generate java tests
        run: python3 ml_model_emulator.py && ls
          
      - name: Commit changes
        run: |
          git config --global user.name 'trnsprntt'
          git config --global user.email 'olya.chernukhina@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "Automated tests generation"
          git push
          
      
#       - name: Test V_219165
#         shell: bash
#         run: |
#           cd src/tests/
#           java -ea TestStig.java
      
      # - name: execute tests
      #   run: java -cp /absolute/path/for/compiled/classes:/absolute/path/to/junit-4.12.jar:/absolute/path/to/hamcrest-core-1.3.jar org.junit.runner.JUnitCore your.package.TestClassName


        


