name: tests run prototype

on:
  workflow_dispatch:
  push:
    paths:
    - 'TARGET_FOLDER/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # checkout changes
      - uses: actions/checkout@v2

      # check that conforms to V-238204
      - name: "V-238204"
        run: cat /boot/grub/grub.cfg && grep -i password /boot/grub/grub.cfg
      
      # # install java to run tests
      # - name: java
      #   uses: actions/setup-java@v2
      
      # - name: execute tests
      #   run: java -cp /absolute/path/for/compiled/classes:/absolute/path/to/junit-4.12.jar:/absolute/path/to/hamcrest-core-1.3.jar org.junit.runner.JUnitCore your.package.TestClassName


        


