name: tests run prototype

on:
  workflow_dispatch:
  push:
    paths:
    - 'TARGET_FOLDER/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # checkout changes
      - uses: actions/checkout@v2

      # check that conforms to V-238204
#       - name: "V-238204"
#         run: cat /etc/pam.d/login && grep pam_lastlog /etc/pam.d/login
        
      - name: Setup java11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          
      - name: Generate java tests
        run: python3 ml_model_emulator.py
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      
#       - name: Test V_219165
#         shell: bash
#         run: |
#           cd src/tests/
#           java -ea TestStig.java
      
      # - name: execute tests
      #   run: java -cp /absolute/path/for/compiled/classes:/absolute/path/to/junit-4.12.jar:/absolute/path/to/hamcrest-core-1.3.jar org.junit.runner.JUnitCore your.package.TestClassName


        


