name: on new requirements push

on:
  workflow_dispatch:
  push:
    paths:
    - 'requirements/**'

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    steps:
      # checkout changes
      - uses: actions/checkout@v2
          
      - name: Generate java tests
        run: python3 ml_model_emulator.py
          
      - name: Commit changes
        run: |
          git config --global user.name 'trnsprntt'
          git config --global user.email 'olya.chernukhina@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "Automated tests generation"
          git push


        


