name: Run java tests

on:
  workflow_dispatch:
#   push:
#     paths:
#       - 'src/tests/*.java'

jobs:
  run_tests:
    name: Run java tests
    runs-on: ubuntu-20.04
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      # setup java11
      - name: Setup java11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Execute tests
        run: cd src/tests/ && java -ea *.java

